// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBr1cke8O6AaXa2tXy07pvt6BV4SSFON1E',
    appId: '1:506177634076:web:ab6ccce6bb80e21565c4d9',
    messagingSenderId: '506177634076',
    projectId: 'authentication-9fb95',
    authDomain: 'authentication-9fb95.firebaseapp.com',
    storageBucket: 'authentication-9fb95.appspot.com',
    measurementId: 'G-KC8MJTF21R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzAyKMGSknnbskKtqSGFR8aw8LCelPbKk',
    appId: '1:506177634076:android:6cbd9fa288b4ec4b65c4d9',
    messagingSenderId: '506177634076',
    projectId: 'authentication-9fb95',
    storageBucket: 'authentication-9fb95.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpgi6ucnpX7Qln5dmPOuHZtrw-i-7V964',
    appId: '1:506177634076:ios:1349aab0c378bd0365c4d9',
    messagingSenderId: '506177634076',
    projectId: 'authentication-9fb95',
    storageBucket: 'authentication-9fb95.appspot.com',
    androidClientId: '506177634076-ck0u9bm2jm9f5npkjg84jo130c4ucv80.apps.googleusercontent.com',
    iosClientId: '506177634076-eohct2090nki668f1pegsgi64qrf2ngv.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication9',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpgi6ucnpX7Qln5dmPOuHZtrw-i-7V964',
    appId: '1:506177634076:ios:1349aab0c378bd0365c4d9',
    messagingSenderId: '506177634076',
    projectId: 'authentication-9fb95',
    storageBucket: 'authentication-9fb95.appspot.com',
    androidClientId: '506177634076-ck0u9bm2jm9f5npkjg84jo130c4ucv80.apps.googleusercontent.com',
    iosClientId: '506177634076-eohct2090nki668f1pegsgi64qrf2ngv.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication9',
  );
}
